- server/requirements.txt
- server/src/db_client.py
secrets necessary are on notion
> basic dbclient

- .github/workflows/heartbeat.yml
Previously, heartbeat ran every 5th minute of the hour. This fixes it to check every 5 minutes.
> Update heartbeat to every 5 minutes

- .github/workflows/backendCI.yml
- .github/workflows/frontendCI.yml
This PR edits when CI is run for both frontend and backend
- for all pull requests
- after merging to main / dev
> [fix] update CI to run on all PR and push to main

- server/Pipfile
- Current CD is down: https://github.com/SyncM8/syncm8/runs/4131713389?check_suite_focus=true
> [fix] CD migration blocker

- README.md
Added Mit license badge.
None.
None.
> [feat] Add Mit license.

- bin/dev
`bin/dev setup` now ensures pre-commit runs before pushing instead of before commiting.
> [feat] Move pre-commit to pre-push.

- .github/workflows/prTitle.yml
- README.md
Add github action to enforce pr title conventions.
> [feat] Add pr-title convention enforcement

- client/src/api.ts
- client/src/pages/App/App.tsx
- client/src/pages/Header/Header.test.tsx
- client/src/pages/Header/Header.tsx
- server/src/api.py
- server/tests/test_api.py
- This PR allows the user to logout
https://user-images.githubusercontent.com/12789302/140692960-f276ff24-8a88-4922-8ffb-dd6ab360a2c4.mov
> [feat] Logout user

- .github/workflows/prTitle.yml
- server/Pipfile
- server/Pipfile.lock
Fix dependabot security dependency and added dev dependencies.
> [chore] Update dependencies and add dev dependencies.

- .dockerignore
- .github/workflows/prTitle.yml
- .pre-commit-config.yaml
- bin/dev
Add a pre-commit hook to ensure you don't change requirements files without also changing the lock files.
ReqLockHook: https://github.com/EpicPi/ReqLockHook
> [feat] Add requirements lock file check for pipfile and package.json

- .github/workflows/actionDependabot.yml
- .github/workflows/devDockerBuild.yml
- Dockerfile
> try manually do it

- .github/workflows/prTitle.yml
- .github/workflows/pre-commit.yml
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #84
* #76
* #75
* #74
* #73
* #72
* #71
* __->__ #85
Remove stipulation that prTitle and pre-commit must be run on main or dev.
> [chore] Make all pr actions work for ghstack.

- .dockerignore
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #84
* #76
* #75
* #74
* #73
* #72
* __->__ #71
* #85
Add more files to dockerignore.
> [chore] Make Dockerignore more aggresive.

- README.md
- update readme with node and docker links
- remove step about ecr because pull happens automaticallly
> [chore] update README with links and remove ecr pull step

- .github/workflows/prTitle.yml
This PR has further restrictions on PR:
- must start with either `[chore]` `[feat]` [migr]` or `[fix]`
- must have space after the tag
- must have capital character after the space
- must not have a period at the end
> [chore] Update PR Title requirements

- .github/workflows/heartbeat.yml
Make heartbeat rely on http code rather than text
> [fix] Make heartbeat rely on http code rather than text

- README.md
- bin/dev
- Add info on which files are affected by pre-commit.
> [chore] Add details on pre-commit process

- server/tests/gql/test_resolver.py
Refactor tests for `resolve_assign_mates` to separate parts, no business logic changed:
- setup data in the DB
- test positive case
- test 3 failure cases
> [fix] Separate setup and tests for resolve_assign_mates

- .github/workflows/devDockerBuild.yml
- Dockerfile
- bin/dev
- bin/infra
- docker-compose.yml
- server/Pipfile
- server/Pipfile.lock
- server/src/clients/mysql.py
Add mysql docker container.
To run dev environment after this pr lands:
1. bin/dev pull
2. bin/dev py-reqs
3. bin/dev up
- [ x] End-to-End
> [feat] Add Mysql docker container

- bin/infra
Change bin/infra script to be aware of versions instead of pulling/pushing `latest`
> [fix] Bin/infra pull pulls and pushes correct image now

- client/src/components/FamilyDroppable/FamilyDroppable.test.tsx
> [fix] Correct FamilyDroppable.test.tsx

- bin/dev
Add back dockerComposeRun method that got deleted by an overzealous piyush.
> [fix] Fix the bin/dev missing dockerComposeRun

- README.md
Changed the order of instruction for installing dev.env file. This is needed before py-req.
> [fix] Update README.md

- .github/dependabot.yml
Set up dependabot so we don't have to worry about manually updating npm, pipenv, or gh actions.
> [feat] Set up dependabot

- .github/dependabot.yml
- .github/workflows/prTitle.yml
Change dependabot config to pre-pend the `[chore] ` tag and set reviewers to `Syncm8/devs`
> [fix] Change dependabot pr title and reviewers

- .github/dependabot.yml
Create a new team for dependency-related updates
> [feat] Create new team for dependabot updates

- README.md
> [chore] Add lgtm badges

- .github/workflows/heartbeat.yml
> [chore] Turn off automated heartbeat
